name: Quality

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  flutter-quality:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Root checks
        shell: pwsh
        run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter pub publish --dry-run

      - name: Example checks
        shell: pwsh
        working-directory: example
        run: |
          flutter pub get
          flutter analyze
          flutter test

      - name: Mobile preview checks
        shell: pwsh
        working-directory: example/mobile_preview
        run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter build web --base-href /mobile_preview/ --pwa-strategy=none

      - name: Build docs web
        shell: pwsh
        run: |
          ./tool/build_docs.ps1 -Flutter flutter
